### ISSUE TITLE
AvaliacaoA4 - Smells

### ISSUE THREAD

**Issue by marianocho** [pedropiin/olympiquiz#40]
Smell 1 - Bloaters (Long class)
- A classe Login.js contém muitas linhs de código. Para resolver isto basta extrair algumas partes do código e transformá-las em componentes separadas, no caso, criamos duas componentes novas que substituíram trechos de código. As duas componentes são SignIn e SignUp. 
#39

**Comment by marianocho** [comment]
Smell 2 - Dispensables (Duplicate code)
- A classe Login.js/Login.css e Playing.js/Playing.css possuiam códigos duplicados, no caso, o botão de voltar ("BackButton"). 
- Para resolver esta redundância, extraímos a nova classe BackButton das classes que repetiam seu uso. Em seguida, importamos esta nova classe nos dois arquivos que a utilizam. 
#44

**Comment by pedropiin** [comment]
Smell 3 - Bloater (Long Method)
- O método validateSignUp() estava muito longo, estendendo-se por mais de 30 linhas de código.
- Buscando resolver esse problema, criei novos métodos (completeSignUp e encryptStore) que realizam funções antes realizadas todas juntas no método validadeSignUp(). Assim, o código fica mais claro, e cada método fica associado à apenas uma função.
#45
